//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Construction Set Extender.rc
//
#define DLG_TEXTEDIT                    9
#define DLG_TESFILE                     104
#define DLG_CONSOLE                     106
#define IDR_MENU1                       107
#define IDD_DIALOG1                     110
#define DLG_IDLE                        110
#define DLG_GLOBALSCRIPT                111
#define DLG_TESCOMBOBOX                 112
#define DLG_BINDSCRIPT                  114
#define DLG_COPYPATH                    116
#define IDR_MENU2                       117
#define IDR_MENU3                       118
#define IDR_MENU4                       119
#define IDR_MENU5                       120
#define IDR_MENU6                       121
#define IDD_DIALOG2                     122
#define DLG_MANAGETOOLS                 122
#define IDB_BITMAP1                     123
#define BITMAP_SPLASH                   123
#define DLG_SCRIPTEDIT                  188
#define EDIT_TEXTLINE                   1002
#define BTN_OK                          1003
#define BTN_CANCEL                      1004
#define BTN_ESP                         1004
#define BTN_ESM                         1005
#define BTN_ADDTOOL                     1005
#define EDIT_CONSOLE                    1006
#define BTN_REMOVETOOL                  1006
#define BTN_MOVEUP                      1007
#define IDC_EDIT1                       1008
#define EDIT_CMDBOX                     1008
#define EDIT_SCRIPT                     1008
#define EDIT_QUESTID                    1008
#define EDIT_EDITORID                   1008
#define EDIT_PATH                       1008
#define BTN_MOVEDOWN                    1008
#define STC_TYPE                        1009
#define IDC_EDIT2                       1009
#define EDIT_DELAY                      1009
#define EDIT_REFEDITORID                1009
#define EDIT_TITLE                      1009
#define IDC_RICHEDIT21                  1010
#define EDIT_QUEST                      1010
#define EDIT_SCRIPTID                   1010
#define EDIT_CMDLINE                    1010
#define EDIT_INITDIR                    1011
#define IDC_COMBO1                      1012
#define COMBO_FORMLIST                  1012
#define BTN_SELECTCMDLINE               1012
#define BTN_SELECTCMDLINE2              1013
#define BTN_SELECTINITDIR               1013
#define BTN_PARENTCELL                  1014
#define RADIO_EXISTFORM                 1016
#define RADIO_NEWFORM                   1017
#define CHECK_QUEST_STARTGAMEENABLED    1018
#define CHECK_QUEST_REPEATEDSTAGES      1019
#define RADIO_QUEST                     1020
#define RADIO_OBJECT                    1021
#define IDC_BUTTON1                     1021
#define BTN_STARTMOUSEHOOK              1021
#define CHECK_OBJECTTOKEN_QUESTITEM     1022
#define RADIO_OBJECTTOKEN               1023
#define LISTBOX_TOOLLIST                1023
#define RADIO_OBJECTREFERENCE           1024
#define BTN_CLOSE                       1024
#define CHECK_OBJECTREFERENCE_DISABLED  1025
#define EDIT_SCTX                       1228
#define DLG_ASSETSEL                    9800
#define BTN_FILEB                       9801
#define BTN_BSAB                        9802
#define BTN_EDITPATH                    9803
#define BTN_CLEARPATH                   9804
#define BTN_COPYPATH                    9805
#define DATA_QUICKLOAD                  9900
#define MAIN_DATA_SAVEAS                9901
#define MAIN_WORLD_BATCHEDIT            9902
#define RENDER_BATCHEDIT                9902
#define MAIN_VIEW_CONSOLEWINDOW         9903
#define MAIN_VIEW_MODIFIEDRECORDS       9904
#define MAIN_DATA_CSEPREFERENCES        9905
#define MAIN_VIEW_DELETEDRECORDS        9906
#define DATA_SETSTARTUPPLUGIN           9906
#define POPUP_SETFORMID                 9907
#define POPUP_MARKUNMODIFIED            9908
#define POPUP_JUMPTOUSEINFOLIST         9909
#define POPUP_UNDELETE                  9910
#define MAIN_WORLD_UNLOADCELL           9911
#define MAIN_GAMEPLAY_GLOBALSCRIPT      9912
#define POPUP_EDITBASEFORM              9913
#define MAIN_LAUNCHGAME                 9914
#define RACE_COPYHAIR                   9915
#define RACE_COPYEYES                   9916
#define POPUP_TOGGLEVISIBILITY          9917
#define POPUP_TOGGLECHILDRENVISIBILITY  9918
#define POPUP_ADDTOTAG                  9919
#define MAIN_VIEW_TAGBROWSER            9920
#define RENDER_GROUPSELECTION           9921
#define RENDER_UNGROUPSELECTION         9922
#define MAIN_DATA_SETWORKSPACE          9923
#define MAIN_DATA_SAVEESPMASTERS        9924
#define POPUP_SHOWOVERRIDES				9925
#define ID_CLEARCONSOLE                 40001
#define CONSOLE_POPUP                   40002
#define ID_CONSOLESETTINGS              40003
#define ID_CONSOLESETTINGS_CLEARCONSOLE 40004
#define CONSOLEMENU_CLEARCONSOLE        40005
#define ID_CONSOLESETTINGS_ALWAYSONTOP  40006
#define CONSOLESETTINGS_ALWAYSONTOP     40007
#define CONSOLEMENU_ALWAYSONTOP         40008
#define ID_CONSOLESETTINGS_HIDECONSOLE  40009
#define CONSOLEMENU_HIDE                40010
#define CONSOLEMENU_HIDECONSOLE         40011
#define ID_ALIGNSELECTION_BYXAXIS       40012
#define ID_ALIGNSELECTION_BYYAXIS       40013
#define ID_ALIGNSELECTION_BYZAXIS       40014
#define ID_SELECTIONGROUPING_GROUPSELECTION 40015
#define ID_SELECTIONGROUPING_UNGROUPSELECTION 40016
#define ID_SELECTIONFREEZING_FREEZESELECTION 40017
#define ID_SELECTIONFREEZING_UNFREEZESELECTION 40018
#define ID_SELECTIONVISIBILITY_TOGGLESELECTIONVISIBILITY 40019
#define ID_SELECTIONVISIBILITY_TOGGLESELECTIONCHILDRENVISIBILITY 40020
#define ID_SELECTIONGROUPING_GROUP      40021
#define ID_SELECTIONGROUPING_UNGROUP    40022
#define ID_SELECTIONFREEZING_FREEZE     40023
#define ID_SELECTIONFREEZING_UNFREEZE   40024
#define ID_SELECTIONVISIBILITY_TOGGLEVISIBILITY 40025
#define ID_SELECTIONVISIBILITY_TOGGLECHILDRENVISIBILITY 40026
#define ID_TOOLS_MANAGE                 40027
#define ID_CONSOLESETTINGS_OPENDEBUGLOG 40028
#define CONSOLEMENU_OPENDEBUGLOG        40029
#define ID_SELECTIONVISIBILITY_SHOWALL  40030


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
