//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Construction Set Extender.rc
//
#define IDR_MENU1                       107
#define IDD_DIALOG1                     110
#define IDR_MENU2                       117
#define IDR_MENU3                       118
#define IDR_MENU4                       119
#define IDR_MENU5                       120
#define IDR_MENU6                       121
#define IDD_DIALOG2                     122
#define IDB_BITMAP1                     123
#define BITMAP_SPLASH                   123
#define IDR_MENU7                       124
#define BITMAP_ADORINGFAN               127
#define IDR_MENU8                       129
#define EDIT_DESC                       1000
#define EDIT_TEXTLINE                   1002
#define BTN_OK                          1003
#define BTN_CANCEL                      1004
#define BTN_ESP                         1004
#define BTN_ESM                         1005
#define BTN_ADDTOOL                     1005
#define EDIT_CONSOLE                    1006
#define BTN_REMOVETOOL                  1006
#define BTN_MOVEUP                      1007
#define IDC_EDIT1                       1008
#define EDIT_CMDBOX                     1008
#define EDIT_SCRIPT                     1008
#define EDIT_QUESTID                    1008
#define EDIT_EDITORID                   1008
#define EDIT_PATH                       1008
#define BTN_MOVEDOWN                    1008
#define EDIT_NAME                       1008
#define LV_INILIST                      1008
#define IDC_EDIT2                       1009
#define EDIT_DELAY                      1009
#define EDIT_REFEDITORID                1009
#define EDIT_TITLE                      1009
#define EDIT_VALUE                      1009
#define IDC_RICHEDIT21                  1010
#define EDIT_QUEST                      1010
#define EDIT_SCRIPTID                   1010
#define EDIT_CMDLINE                    1010
#define EDIT_SCRIPTTEXT                 1010
#define EDIT_INITDIR                    1011
#define IDC_COMBO1                      1012
#define COMBO_FORMLIST                  1012
#define BTN_SELECTCMDLINE               1012
#define BTN_SELECTCMDLINE2              1013
#define BTN_SELECTINITDIR               1013
#define BTN_PARENTCELL                  1014
#define RADIO_EXISTFORM                 1016
#define RADIO_NEWFORM                   1017
#define CHECK_QUEST_STARTGAMEENABLED    1018
#define CHECK_QUEST_REPEATEDSTAGES      1019
#define RADIO_QUEST                     1020
#define RADIO_OBJECT                    1021
#define IDC_BUTTON1                     1021
#define BTN_STARTMOUSEHOOK              1021
#define BTN_ADDGLOBALNUM                1021
#define BTN_APPLY                       1021
#define BTN_COMPILE                     1021
#define BTN_EXTRACTFILE                 1021
#define CHECK_OBJECTTOKEN_QUESTITEM     1022
#define BTN_ADDGLOBALSTR                1022
#define RADIO_OBJECTTOKEN               1023
#define LISTBOX_TOOLLIST                1023
#define BTN_REMOVE                      1023
#define RADIO_OBJECTREFERENCE           1024
#define BTN_CLOSE                       1024
#define CHECK_OBJECTREFERENCE_DISABLED  1025
#define LISTBOX_GLOBALLIST              1025
#define BTN_APPLYCHANGES                1027
#define LBL_TITLE                       1029
#define LBL_DESC                        1030
#define PICT_IMG                        1031
#define BTN_SAVE                        1033
#define DLG_TEXTEDIT                    5009
#define DLG_TESFILE                     5104
#define DLG_CONSOLE                     5106
#define DLG_IDLE                        5110
#define DLG_GLOBALSCRIPT                5111
#define DLG_TESCOMBOBOX                 5112
#define DLG_BINDSCRIPT                  5114
#define DLG_COPYPATH                    5116
#define DLG_MANAGETOOLS                 5122
#define DLG_CSASGLOBALS                 5125
#define DLG_ACHIEVEMENTUNLOCKED         5126
#define DLG_EDITRESULTSCRIPT            5128
#define DLG_ASSETSEL                    9800
#define BTN_FILEB                       9801
#define BTN_BSAB                        9802
#define BTN_EDITPATH                    9803
#define BTN_CLEARPATH                   9804
#define BTN_COPYPATH                    9805
#define ID_CLEARCONSOLE                 41001
#define CONSOLE_POPUP                   41002
#define ID_CONSOLESETTINGS              41003
#define ID_CONSOLESETTINGS_CLEARCONSOLE 41004
#define CONSOLEMENU_CLEARCONSOLE        41005
#define ID_CONSOLESETTINGS_ALWAYSONTOP  41006
#define CONSOLESETTINGS_ALWAYSONTOP     41007
#define CONSOLEMENU_ALWAYSONTOP         41008
#define ID_CONSOLESETTINGS_HIDECONSOLE  41009
#define CONSOLEMENU_HIDE                41010
#define CONSOLEMENU_HIDECONSOLE         41011
#define ID_ALIGNSELECTION_BYXAXIS       41012
#define ID_ALIGNSELECTION_BYYAXIS       41013
#define ID_ALIGNSELECTION_BYZAXIS       41014
#define ID_SELECTIONGROUPING_GROUPSELECTION 41015
#define ID_SELECTIONGROUPING_UNGROUPSELECTION 41016
#define ID_SELECTIONFREEZING_FREEZESELECTION 41017
#define ID_SELECTIONFREEZING_UNFREEZESELECTION 41018
#define ID_SELECTIONVISIBILITY_TOGGLESELECTIONVISIBILITY 41019
#define ID_SELECTIONVISIBILITY_TOGGLESELECTIONCHILDRENVISIBILITY 41020
#define ID_SELECTIONGROUPING_GROUP      41021
#define ID_SELECTIONGROUPING_UNGROUP    41022
#define ID_SELECTIONFREEZING_FREEZE     41023
#define ID_SELECTIONFREEZING_UNFREEZE   41024
#define ID_SELECTIONVISIBILITY_TOGGLEVISIBILITY 41025
#define ID_SELECTIONVISIBILITY_TOGGLECHILDRENVISIBILITY 41026
#define ID_TOOLS_MANAGE                 41027
#define ID_CONSOLESETTINGS_OPENDEBUGLOG 41028
#define CONSOLEMENU_OPENDEBUGLOG        41029
#define ID_SELECTIONVISIBILITY_SHOWALL  41030
#define ID_CONSOLESETTINGS_OPENCHANGELOG 41031
#define CONSOLEMENU_OPENCHANGELOG       41032
#define ID_CSAS_GLOBALDATA              41033
#define ID_CSAS_RELOADGLOBALSCRIPTS     41034
#define ID_SAVEOPTIONS_SAVELOADEDESP    41035
#define ID_SAVEOPTIONS_PREVENTCHANGESTOFILETIMESTAMPS 41036
#define ID_SELECTIONFREEZING_THAWALLINCELL 42000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6000
#define _APS_NEXT_COMMAND_VALUE         42001
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
