#pragma once

#include "..\ScriptCommandInfo.h"

namespace CSAutomationScript
{
	void		RegisterFormCommands();

	DECLARE_CSASCOMMAND(GetFormByEditorID);
	DECLARE_CSASCOMMAND(GetFormByFormID);

	DECLARE_CSASCOMMAND(GetEditorID);
	DECLARE_CSASCOMMAND(GetFormType);

	DECLARE_CSASCOMMAND(GetBFCFullName);
	DECLARE_CSASCOMMAND(GetBFCDescription);
	DECLARE_CSASCOMMAND(GetBFCTexturePath);
	DECLARE_CSASCOMMAND(GetBFCModelPath);
	DECLARE_CSASCOMMAND(GetBFCModelBoundRadius);
	DECLARE_CSASCOMMAND(GetBFCScript);
	DECLARE_CSASCOMMAND(GetBFCUses);
	DECLARE_CSASCOMMAND(GetBFCValue);
	DECLARE_CSASCOMMAND(GetBFCHealth);
	DECLARE_CSASCOMMAND(GetBFCWeight);
	DECLARE_CSASCOMMAND(GetBFCQuality);
	DECLARE_CSASCOMMAND(GetBFCAttackDamage);
	DECLARE_CSASCOMMAND(GetBFCAttributes);
	DECLARE_CSASCOMMAND(GetBFCSpellListEntries);
	DECLARE_CSASCOMMAND(GetBFCLeveledListEntries);
	DECLARE_CSASCOMMAND(GetBFCLeveledListChanceNone);
	DECLARE_CSASCOMMAND(GetBFCContainerEntries);
	DECLARE_CSASCOMMAND(GetBFCActorBaseDataNPCFlags);
	DECLARE_CSASCOMMAND(GetBFCActorBaseDataCreatureFlags);
	DECLARE_CSASCOMMAND(GetBFCActorBaseDataFactionList);
	DECLARE_CSASCOMMAND(GetBFCActorBaseDataMagicka);
	DECLARE_CSASCOMMAND(GetBFCActorBaseDataFatigue);
	DECLARE_CSASCOMMAND(GetBFCActorBaseDataBarterGold);
	DECLARE_CSASCOMMAND(GetBFCActorBaseDataLevel);
	DECLARE_CSASCOMMAND(GetBFCAIFormAIStats);
	DECLARE_CSASCOMMAND(GetBFCAIFormAIServiceFlags);
	DECLARE_CSASCOMMAND(GetBFCAIFormAITrainingSkill);
	DECLARE_CSASCOMMAND(GetBFCAIFormAITrainingLevel);
	DECLARE_CSASCOMMAND(GetBFCAIFormAIPackageList);
	DECLARE_CSASCOMMAND(GetBFCReactionFormReactionEntries);
	DECLARE_CSASCOMMAND(GetBFCSoundFilePath);
	DECLARE_CSASCOMMAND(GetBFCBipedModelSlotMask);
	DECLARE_CSASCOMMAND(GetBFCBipedModelFlags);
	DECLARE_CSASCOMMAND(GetBFCBipedModelMaleBipedModelPath);
	DECLARE_CSASCOMMAND(GetBFCBipedModelFemaleBipedModelPath);
	DECLARE_CSASCOMMAND(GetBFCBipedModelMaleGroundModelPath);
	DECLARE_CSASCOMMAND(GetBFCBipedModelFemaleGroundModelPath);
	DECLARE_CSASCOMMAND(GetBFCBipedModelMaleIconPath);
	DECLARE_CSASCOMMAND(GetBFCBipedModelFemaleIconPath);
	DECLARE_CSASCOMMAND(GetBFCBipedModelMaleBipedModelPath);
	DECLARE_CSASCOMMAND(GetBFCEnchantableFormEnchantment);
	DECLARE_CSASCOMMAND(GetBFCEnchantableFormType);
	DECLARE_CSASCOMMAND(GetBFCProduceFormIngredient);
	DECLARE_CSASCOMMAND(GetBFCProduceFormChance);
	DECLARE_CSASCOMMAND(GetBFCModelListModels);

	DECLARE_CSASCOMMAND(SetBFCFullName);
	DECLARE_CSASCOMMAND(SetBFCDescription);
	DECLARE_CSASCOMMAND(SetBFCTexturePath);
	DECLARE_CSASCOMMAND(SetBFCModelPath);
	DECLARE_CSASCOMMAND(SetBFCModelBoundRadius);
	DECLARE_CSASCOMMAND(SetBFCScript);
	DECLARE_CSASCOMMAND(SetBFCUses);
	DECLARE_CSASCOMMAND(SetBFCValue);
	DECLARE_CSASCOMMAND(SetBFCHealth);
	DECLARE_CSASCOMMAND(SetBFCWeight);
	DECLARE_CSASCOMMAND(SetBFCQuality);
	DECLARE_CSASCOMMAND(SetBFCAttackDamage);
	DECLARE_CSASCOMMAND(SetBFCAttribute);
	DECLARE_CSASCOMMAND(SetBFCLeveledListChanceNone);
	DECLARE_CSASCOMMAND(SetBFCActorBaseDataNPCFlags);
	DECLARE_CSASCOMMAND(SetBFCActorBaseDataCreatureFlags);
	DECLARE_CSASCOMMAND(SetBFCActorBaseDataMagicka);
	DECLARE_CSASCOMMAND(SetBFCActorBaseDataFatigue);
	DECLARE_CSASCOMMAND(SetBFCActorBaseDataBarterGold);
	DECLARE_CSASCOMMAND(SetBFCActorBaseDataLevel);
	DECLARE_CSASCOMMAND(SetBFCAIFormAIStats);
	DECLARE_CSASCOMMAND(SetBFCAIFormAIServiceFlags);
	DECLARE_CSASCOMMAND(SetBFCAIFormAITrainingSkill);
	DECLARE_CSASCOMMAND(SetBFCAIFormAITrainingLevel);
	DECLARE_CSASCOMMAND(SetBFCSoundFilePath);
	DECLARE_CSASCOMMAND(SetBFCBipedModelSlotMask);
	DECLARE_CSASCOMMAND(SetBFCBipedModelFlags);
	DECLARE_CSASCOMMAND(SetBFCBipedModelMaleBipedModelPath);
	DECLARE_CSASCOMMAND(SetBFCBipedModelFemaleBipedModelPath);
	DECLARE_CSASCOMMAND(SetBFCBipedModelMaleGroundModelPath);
	DECLARE_CSASCOMMAND(SetBFCBipedModelFemaleGroundModelPath);
	DECLARE_CSASCOMMAND(SetBFCBipedModelMaleIconPath);
	DECLARE_CSASCOMMAND(SetBFCBipedModelFemaleIconPath);
	DECLARE_CSASCOMMAND(SetBFCBipedModelMaleBipedModelPath);
	DECLARE_CSASCOMMAND(SetBFCEnchantableFormEnchantment);
	DECLARE_CSASCOMMAND(SetBFCEnchantableFormType);
	DECLARE_CSASCOMMAND(SetBFCProduceFormIngredient);
	DECLARE_CSASCOMMAND(SetBFCProduceFormChance);
}